version: '2'

services:
  web:
    env_file: .env
    image: lagotto/lagotto:5-1-unstable
    ports:
      - "8050:80"
  db:
    env_file: .env
    image: mysql:5.6
    ports:
      - "3306:3306"
  redis:
    image: redis:2.8
  memcached:
    image: memcached:1.4.31
